name: Format Java Code

on:
  pull_request:
    branches:
      - main

permissions: 
    pull-requests: write
    contents: write

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'
            - name: Cache Gradle packages
              uses: actions/cache@v3
              with:
                  path: ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: |
                    ${{ runner.os }}-gradle-
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Run SpotlessApply
              run: ./gradlew spotlessApply
            - name: Commit and Push changes
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                git config --local user.name "github-actions[bot]@user.noreply.github.com"
                git config --local user.email "GitHub Actions Bot"
                git add .
                git commit -m "Apply code formatting"
                # プッシュ前にリモートの変更をプルする
                git pull origin HEAD --rebase
                git push origin HEAD:${{ github.head_ref }} || echo "No changes to commit"
